### ISSUE TITLE
Article worth highlighting.

### ISSUE THREAD

**Issue by stark1tty** [nathanlesage/academics-on-mastodon#125]
Hey! I kind of think this article is worth highlighting at the top of the list- thoughts?

https://netzpolitik.org/2023/a-call-to-action-universities-of-the-world-into-the-fediverse/

**Comment by nathanlesage** [comment]
Personally, I fully agree with this article and would love to see universities do that on a large scale. However, this is not really a list, but a call for action. So the question would be how to properly include it, if at all... so I'm mainly worries about how to include such a link into the list without breaking the list spirit 👀

The addressee of the article are clearly institutions, but those who come to the list are individuals, right?

**Comment by stark1tty** [comment]
Perhaps as a PSA in a small quote box? Doesn't have to be more than a line. The spirit of the list is the Fediverse and I think this article encapsulates it.

**Comment by nathanlesage** [comment]
How about this PSA in the Readme over the server section with the following wording:

> If you would rather like to register on a university server but yours does not offer one, you could attempt to lobby for one by passing on [this call to action](https://netzpolitik.org/2023/a-call-to-action-universities-of-the-world-into-the-fediverse/).

**Comment by stark1tty** [comment]
Yes, love it!

**Comment by nathanlesage** [comment]
Wonderful, it's in!
