### ISSUE TITLE
Include Universities running Mastodon instances? 

### ISSUE THREAD

**Issue by kreynen** [nathanlesage/academics-on-mastodon#145]
I created a PR to add @medlab@social.medlab.host, but I wasn't sure if https://mastodon.mit.edu/ and https://faculty.mastodon.stanford.edu/ belonged on the list. These aren't official Mastodon accounts, but Mastodon instances run by these universities.

**Comment by nathanlesage** [comment]
> These aren't official Mastodon accounts

Nothing is "official Mastodon" except the one or two instances directly run by their team. That's the whole point why this list exists ;) We also have a section for servers. I'll add those two there. (The MIT server was already on the list).

**Comment by N1N74** [comment]
@nathanlesage please include https://social.mpdl.mpg.de/ for Max Planck Society, hosted by Max Planck Digital Library (MPDL). [More info](https://social.mpdl.mpg.de/about). We can also find accounts from the server [here](https://social.mpdl.mpg.de/directory) by filtering for local accounts.
