### ISSUE TITLE
Run md as page?

### ISSUE THREAD

**Issue by trutzig89182** [nathanlesage/academics-on-mastodon#24]
Hey, gerade zufällig drauf gestoßen und vllt. willst du es mal testen: Wenn kein idex.html da ist, müsste github die md einfach als website rendern, wenn du pages from branch main aktivierts, Das wäre ja vielelicht ganz nett, wenn die Github infrastruktur für dei normale Nutzer*in weniger im Vordergrund steht.

**Comment by trutzig89182** [comment]
So, in principle that would work: https://trutzig89182.github.io/academics-on-mastodon/ (will close that site later, just gave it a try).

**Comment by trutzig89182** [comment]
I think, if you just deploy the page from the main branch, it will render the readme.md if there is no index.html.

**Comment by trutzig89182** [comment]
(It is of course not necessary at all to do this. I just remember going to a repository the first time and being confused, what this is all about, and having it rendered as a pages can get rid of this …).

**Comment by nathanlesage** [comment]
Woaoh, that was simple. Now live at https://nathanlesage.github.io/academics-on-mastodon/!
