### ISSUE TITLE
Preview image

### ISSUE THREAD

**Issue by trutzig89182** [nathanlesage/academics-on-mastodon#7]
Perhaps we could take the image down from the md and use it as preview image like so: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview ?

It is a bit in the way in Readme and the social media preview looks rather technical right now.

**Comment by nathanlesage** [comment]
Ah the repository preview image. Yeah, gimme a sec.

**Comment by nathanlesage** [comment]
Done! It'll take a while until the caches of the various servers have refreshed and show the "new" preview image.
